# Site
title: تایپو
description: جواب‌های ساده برای سوال‌های ساده
url: https://typo.ir
logo: Logo.gif
locale: fa

# Left Block Images
background:
  homepage: images/Home.jpg
  post-list: images/Posts.jpg
  default-post: images/Posts.jpg

# Jekyll
permalink: /:title/
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
sass:
  sass_dir: assets/_sass
  style: compressed

email: voxp@pm.me
twitter: voxxp
telegram: voxxp
bitcoin: vox

jekyll-mentions: https://twitter.com

workbox:
  sw_src_filepath: sw.js
  sw_dest_filename: sw.js
  precache_recent_posts_num: 5
  precache_glob_directory: /
  precache_glob_patterns:
    - "{js,css,fonts,assests}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
    - "posts.html":
        - posts/
  precache_glob_ignores: # Optional
    - "assests/fonts/**/*"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-email-protect
  - jekyll-tagging-related_posts
  - jekyll-mentions
  - jekyll-twitter-plugin
  - jekyll-github-metadata
  - jekyll-target-blank
  - jekyll-workbox-plugin

# Headers
webrick:
  headers:
    Referrer-Policy: "strict-origin-when-cross-origin"
    Feature-Policy: "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"
    X-Frame-Options: "SAMEORIGIN"
    X-Xss-Protection: "1; mode=block; report=https://typo.report-uri.com/r/d/xss/enforce"
    X-Content-Type-Options: "nosniff"
    Content-Security-Policy: "default-src 'self'; script-src 'self' data: 'unsafe-inline' platform.twitter.com cdn.syndication.twimg.com syndication.twitter.com www.redditstatic.com *.vimeocdn.com *.akamaized.net platform.instagram.com; object-src 'self' https:; style-src 'self' data: 'unsafe-inline' nezare.ir use.fontawesome.com www.redditmedia.com www.redditstatic.com c.disquscdn.com a.disquscdn.com platform.twitter.com ton.twimg.com *.vimeocdn.com; img-src 'self' data: www.gravatar.com links.services.disqus.com referrer.disqus.com a.disquscdn.com cdn.syndication.twimg.com syndication.twitter.com pbs.twimg.com platform.twitter.com abs.twimg.com www.redditmedia.com www.redditstatic.com; media-src 'self' https:; frame-src 'self' https:; font-src 'self' https:; connect-src 'self' https:; report-uri https://typo.report-uri.com/r/d/csp/wizard"

# Exclude list
include: [_pages, keybase.txt]
exclude:
  [
    README.md,
    Gemfile,
    Gemfile.lock,
    _site,
    src,
    vendor,
    CNAME,
    LICENSE,
    Rakefile,
    .sass-cache,
    .DS_Store,
    vendor,
  ]
